version: "3"
services:
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgresuser
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"