"""init_db

Revision ID: 2f0d40491e88
Revises: 5559a0eb62f3
Create Date: 2024-04-25 10:26:26.227918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f0d40491e88'
down_revision: Union[str, None] = '5559a0eb62f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('idade', sa.Integer(), nullable=False))
    op.add_column('atletas', sa.Column('centro_treinamento_id', sa.Integer(), nullable=False))
    op.drop_constraint('atletas_centros_treinamento_id_fkey', 'atletas', type_='foreignkey')
    op.create_foreign_key(None, 'atletas', 'centros_treinamento', ['centro_treinamento_id'], ['pk_id'])
    op.drop_column('atletas', 'centros_treinamento_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('centros_treinamento_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'atletas', type_='foreignkey')
    op.create_foreign_key('atletas_centros_treinamento_id_fkey', 'atletas', 'centros_treinamento', ['centros_treinamento_id'], ['pk_id'])
    op.drop_column('atletas', 'centro_treinamento_id')
    op.drop_column('atletas', 'idade')
    # ### end Alembic commands ###
